FROM python:3.10-slim
WORKDIR /app
COPY nlp-rule-extractor/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY nlp-rule-extractor/ .
EXPOSE 5001
CMD ["gunicorn", "--bind", "0.0.0.0:5001", "app:app"]
