spring:
  application:
    name: policy-decision-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pqvcf_regulations}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

pqvcf:
  pap:
    grpc:
      host: ${PQVCF_PAP_GRPC_HOST:localhost}
      port: ${PQVCF_PAP_GRPC_PORT:9093}
  pip:
    grpc:
      host: ${PQVCF_PIP_GRPC_HOST:localhost}
      port: ${PQVCF_PIP_GRPC_PORT:9094}

server:
  port: 8085

logging:
  level:
    root: INFO
    com.pqvcf: DEBUG
